# Generated by Django 2.2.2 on 2019-06-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190628_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
    ]
