# Generated by Django 2.2.2 on 2019-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190628_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='activity_type',
            field=models.CharField(choices=[('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1),
        ),
    ]
